[package]
name = "gcd"
version = "0.1.0"
edition = "2021"
author = "Dae Choi <daechoi@outlook.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
